import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import styled from "styled-components";
import axios from "axios";
import List from "./components/List";
import { useEffect, useState } from "react";

export const Container = styled.div`
  max-width: 100vw;
  height: fit-content;
`;

export default function Home() {
  const [data, setData] = useState([]);

  useEffect(() => {
    const done = async () => {
      const { data } = await axios.get(
        "https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json"
      );
      setData(data);
    };
    done();
  }, []);

  return (
    <Container className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {console.log(data)} */}
      <List data={data}></List>
    </Container>
  );
}
